name: Deploy to Vercel
description: Deploy the app using Vercel CLI

inputs:
  app-directory:
    description: 'The directory of the app to be deployed'
    required: true
  vercel-project-id:
    description: 'The Vercel project ID for the app'
    required: true
  vercel-token:
    description: 'The Vercel authentication token'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install global dependencies
      shell: bash
      run: |
        npm install -g pnpm
        npm install -g vercel@canary

    - name: Change to app directory
      shell: bash
      run: cd ${{ inputs.app-directory }}

    - name: Install project dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Pull Vercel environment information
      shell: bash
      env: 
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      run: vercel pull --yes --environment=preview --token=${{ inputs.vercel-token }}

    - name: Build project artifacts
      shell: bash
      run: vercel build --token=${{ inputs.vercel-token }}

    - name: Deploy project artifacts to Vercel
      
      shell: bash
      run: vercel deploy --prebuilt --token=${{ inputs.vercel-token }}
