name: Contentful apps deployment

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App to deploy'
        type: choice
        required: true
        options:
          - 'dynamic-forms-preview'
          - 'dynamic-forms-form-settings'
          - 'dynamic-forms-subscriptions'
        default: 'dynamic-forms-preview'
      version:
        description: 'The branch, tag or SHA to checkout'
        required: true
      environment:
        description: 'Deployment environment'
        type: choice
        required: true
        options:
          - 'dev'
          - 'staging'
          - 'production'
        default: 'dev'

permissions:
  contents: write

jobs:
  deploy:
    name: 'Deploy ${{ github.event.inputs.app }} to ${{ github.event.inputs.environment }} (${{ github.event.inputs.version }})'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    timeout-minutes: 45
    env:
      CONTENTFUL_ORG_ID: ${{ secrets.CONTENTFUL_ORG_ID }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_API_ACCESS_TOKEN }}
      CONTENTFUL_SHARED_CONTENT_PREVIEW_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SHARED_CONTENT_PREVIEW_ACCESS_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: './.github/actions/setup-pnpm'

      - name: Set environment variables
        run: |
          if [ "${{ github.event.inputs.app }}" == "dynamic-forms-form-settings" ]; then
            echo "CONTENTFUL_APP_DEF_ID=${{ secrets.CONTENTFUL_APP_ID_DYNAMIC_FORMS_FORM_SETTINGS }}" >> $GITHUB_ENV  
          elif [ "${{ github.event.inputs.app }}" == "dynamic-forms-subscriptions" ]; then
            echo "CONTENTFUL_APP_DEF_ID=${{ secrets.CONTENTFUL_APP_ID_DYNAMIC_FORMS_SUBSCRIPTION }}" >> $GITHUB_ENV
            echo "VITE_BACKEND_URL=${{ secrets.BACKEND_URL }}" >> $GITHUB_ENV
            echo "VITE_TARGET_CONTENTFUL_ENVIRONMENT=master" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.app }}" == "dynamic-forms-preview" ]; then
            echo "CONTENTFUL_APP_DEF_ID=${{ secrets.CONTENTFUL_APP_ID_DYNAMIC_FORMS_PREVIEW }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}" >> $GITHUB_ENV
            echo "CONTENTFUL_APP_DEF_ID=${{ secrets.CONTENTFUL_APP_ID_DYNAMIC_FORMS_PREVIEW }}" >> $GITHUB_ENV
          fi

      - name: Build and Upload - Contentful App - ${{ github.event.inputs.app }}
        run: |
          pnpm build:contentful-forms-apps
          cd apps/contentful-apps/${{ github.event.inputs.app }}
          pnpm upload
