name: Contentful apps deployment - Manual workflow

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'The name of the app to deploy'
        type: choice
        required: true
        options:
          - 'dynamic-forms-preview'
          - 'dynamic-forms-form-settings'
          - 'dynamic-forms-subscriptions'
        default: 'dynamic-forms-preview'

      environment:
        description: 'Deployment environment'
        type: choice
        required: true
        options:
          - 'dev'
          - 'staging'
          - 'production'
        default: 'dev'

permissions:
  contents: write

jobs:
  map-app-definition:
    runs-on: ubuntu-latest
    name: Map inputs to app definition
    steps:
      - name: Determine App Definition ID
        id: map-app-definition
        run: |
          case "${{ github.event.inputs.app-name }}-${{ github.event.inputs.environment }}" in
            "dynamic-forms-preview-dev") echo "app-definition=a" >> $GITHUB_ENV ;;
            "dynamic-forms-preview-staging") echo "app-definition=b" >> $GITHUB_ENV ;;
            "dynamic-forms-preview-production") echo "app-definition=c" >> $GITHUB_ENV ;;
            "dynamic-forms-form-settings-dev") echo "app-definition=d" >> $GITHUB_ENV ;;
            "dynamic-forms-form-settings-staging") echo "app-definition=e" >> $GITHUB_ENV ;;
            "dynamic-forms-form-settings-production") echo "app-definition=f" >> $GITHUB_ENV ;;
            "dynamic-forms-subscriptions-dev") echo "app-definition=g" >> $GITHUB_ENV ;;
            "dynamic-forms-subscriptions-staging") echo "app-definition=h" >> $GITHUB_ENV ;;
            "dynamic-forms-subscriptions-production") echo "app-definition=i" >> $GITHUB_ENV ;;
            *) echo "Error: Invalid app-name or environment combination!" && exit 1 ;;
          esac

  deploy:
    name: Deploy ${{ github.event.inputs.app-name }} (Contentful ${{ github.event.inputs.environment }})
    uses: ./.github/workflows/reusable-contentful-deploy.yml
    needs: map-app-definition
    with:
      app-name: ${{ github.event.inputs.app-name }}
      app-definition: ${{ needs.steps.map-app-definition.outputs.app-definition }}
      github-environment: ${{ github.event.inputs.environment }}