name: Pull request workflow

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
    branches:
      - master

env:
  CI: true
  HUSKY: 0
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ----------------------------------------
  # Code quality checks
  # ----------------------------------------
 

  # ----------------------------------------
  # Deployments
  # ----------------------------------------
  check-paths:
    name: Check modified paths
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      unified: ${{ steps.paths.outputs.unified }}
      login: ${{ steps.paths.outputs.login }}
      dynamic-forms-preview: ${{ steps.paths.outputs.dynamic-forms-preview }}
      dynamic-forms-form-settings: ${{ steps.paths.outputs.dynamic-forms-form-settings }}
      dynamic-forms-subscriptions: ${{ steps.paths.outputs.dynamic-forms-subscriptions }}
      packages: ${{ steps.paths.outputs.packages }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check paths
        id: paths
        uses: ./.github/actions/check-paths

  get-pr-number:
    name: Get pull request number
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      pr-number: ${{ steps.pr-number.outputs.pr-number }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ./.github/actions/pr-number
        id: pr-number

  unified-web-app-preview-deployment:
    name: Deploy Unified-web App (Vercel Preview)
    if: ${{ needs.check-paths.outputs.unified == 'true' || needs.check-paths.outputs.packages == 'true' }}
    needs: [check-paths, get-pr-number]
    uses: ./.github/workflows/reusable-vercel-deploy.yml
    with:
      app-name: 'Unified-web App'
      github-environment: 'dev'
      vercel-environment: 'preview'
      domains: |
        ${{ needs.get-pr-number.outputs.pr-number }}-pr-domain-1.vercel.app
    secrets: inherit

  login-app-preview-deployment:
    name: Deploy Login App (Vercel Preview)
    if: ${{ needs.check-paths.outputs.login == 'true' || needs.check-paths.outputs.packages == 'true' }}
    needs: [check-paths, get-pr-number]
    uses: ./.github/workflows/reusable-vercel-deploy.yml
    with:
      app-name: 'Login App'
      github-environment: 'dev'
      vercel-environment: 'preview'
      domains: |
        ${{ needs.get-pr-number.outputs.pr-number }}-pr-domain-2.vercel.app
        other-domain.vercel.app
    secrets: inherit

  dynamic-forms-preview-dev-deploy:
    name: Deploy Dynamic Forms Preview (Contentful Dev)
    if: ${{ needs.check-paths.outputs.dynamic-forms-preview == 'true' }}
    needs: [check-paths]
    uses: ./.github/workflows/reusable-contentful-deploy.yml
    with:
      app-name: 'Dynamic Forms Preview'
      app-definition: ''
      github-environment: 'dev'
        
  dynamic-forms-form-settings-dev-deploy:
    name: Deploy Dynamic Forms Form Settings (Contentful Dev)
    if: ${{ needs.check-paths.outputs.dynamic-forms-form-settings == 'true' }}
    needs: [check-paths]
    uses: ./.github/workflows/reusable-contentful-deploy.yml
    with:
      app-name: 'Dynamic Forms Form Settings'
      app-definition: ''
      github-environment: 'dev'
        
  dynamic-forms-subscriptions-dev-deploy:
    name: Deploy Dynamic Forms Subscriptions (Contentful Dev)
    if: ${{ needs.check-paths.outputs.dynamic-forms-subscriptions == 'true' }}
    needs: [check-paths]
    uses: ./.github/workflows/reusable-contentful-deploy.yml
    with:
      app-name: 'Dynamic Forms Subscriptions'
      app-definition: ''
      github-environment: 'dev'