name: Pull request workflow

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
    branches-ignore:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  check-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check paths
        uses: ./.github/actions/check-paths
      - name: Print outputs
        run: |
          echo "Unified: ${{ needs.check-paths.outputs.unified }}"
          echo "Login: ${{ needs.filter.check-paths.login }}"
          echo "Dynamic Forms Preview: ${{ needs.filter.check-paths.dynamic-forms-preview }}"
          echo "Dynamic Forms Form Settings: ${{ needs.filter.check-paths.dynamic-forms-form-settings }}"
          echo "Dynamic Forms Subscriptions: ${{ needs.filter.check-paths.dynamic-forms-subscriptions }}"

  unified-preview-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.unified == 'true' }}
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/vercel
        with:
          app-directory: 'apps/unified'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_UNIFIED_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-environment: 'preview'

  login-preview-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.login == 'true' }}
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/vercel
        with:
          app-directory: 'apps/login'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_LOGIN_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-environment: 'preview'

  # TODO: Add deployment steps for the following apps:
  # dynamic-forms-preview-dev-deploy
  # dynamic-forms-form-settings-dev-deploy
  # dynamic-forms-subscriptions-dev-deploy
