name: Pull request workflow

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
    branches-ignore:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      unified: ${{ steps.filter.outputs.unified }}
      login: ${{ steps.filter.outputs.login }}
    steps:
      - uses: actions/checkout@v4
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            unified:
              - added|modified|deleted: 'apps/unified/**'
            login:
              - added|modified|deleted: 'apps/login/**'

  unified-preview-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.unified == 'true' }}
    steps:
      - uses: ./.github/actions/vercel
        with:
          app-directory: 'apps/unified'
          vercel-project-id: ${{ secrets.VERCEL_UNIFIED_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}

  login-preview-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.login == 'true' }}
    steps:
      - uses: ./.github/actions/vercel
        with:
          app-directory: 'apps/login'
          vercel-project-id: ${{ secrets.VERCEL_LOGIN_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
