name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      unified: ${{ steps.paths.outputs.unified }}
      login: ${{ steps.paths.outputs.login }}
      dynamic-forms-preview: ${{ steps.paths.outputs.dynamic-forms-preview }}
      dynamic-forms-form-settings: ${{ steps.paths.outputs.dynamic-forms-form-settings }}
      dynamic-forms-subscriptions: ${{ steps.paths.outputs.dynamic-forms-subscriptions }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check paths
        id: paths
        uses: ./.github/actions/check-paths

  unified-production-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.unified == 'true' }}
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/vercel
        with:
          app-directory: 'apps/unified'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_UNIFIED_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-environment: 'production'

  login-production-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.login == 'true' }}
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/vercel
        with:
          app-directory: 'apps/login'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_LOGIN_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-environment: 'production'

  # TODO: Add deployment steps for the following apps:
  # dynamic-forms-preview-prod-deploy
  # dynamic-forms-form-settings-prod-deploy
  # dynamic-forms-subscriptions-prod-deploy
