name: Release apps

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  CI: true
  HUSKY: 0
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      prs_created: ${{ steps.release.outputs.prs_created }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
        
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Echo outputs
        run: |
          echo "Releases created: ${{ steps.release.outputs.releases_created }}"
          echo "PRs created: ${{ steps.release.outputs.prs_created }}"
          echo "PR details: $PR_JSON"
          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.number')
          echo "PR number: $PR_NUMBER"
        env:
          PR_JSON: ${{ steps.release.outputs.pr }}
