name: Staging Deployment

on:
  workflow_dispatch:
  push:
    branches: [dev]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      unified: ${{ steps.filter.outputs.unified }}
      login: ${{ steps.filter.outputs.login }}
    steps:
      - uses: actions/checkout@v4
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            unified:
              - added|modified|deleted: 'apps/unified/**'
            login:
              - added|modified|deleted: 'apps/login/**'
            dynamic-forms-preview:
              - added|modified|deleted: 'apps/contentful-apps/dynamic-forms-preview/**'
            dynamic-forms-form-settings:
              - added|modified|deleted: 'apps/contentful-apps/dynamic-forms-form-settings/**'
            dynamic-forms-subscriptions:
              - added|modified|deleted: 'apps/contentful-apps/dynamic-forms-subscriptions/**'

  unified-preview-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.unified == 'true' }}
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/vercel
        with:
          app-directory: 'apps/unified'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_UNIFIED_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-environment: 'preview'

  login-preview-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging
    needs: [check-paths]
    if: ${{ needs.check-paths.outputs.login == 'true' }}
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/vercel
        with:
          app-directory: 'apps/login'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_LOGIN_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-environment: 'preview'

  # TODO: Add deployment steps for the following apps:
  # dynamic-forms-preview-staging-deploy
  # dynamic-forms-form-settings-staging-deploy
  # dynamic-forms-subscriptions-staging-deploy
